import {BuyItemType} from './../src/types/buy';

export const BuyItemsMock: BuyItemType[] = [
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
  {
    id: 0,
    category: 'category',
    product: 'product',
    multiply: 2,
    price: 3,
    email: 'email',
  },
];
