import {BuyItemType} from './../src/types/buy';

export const BuyItemsMock: BuyItemType[] = [
  {
    id: 0,
    category: 'Food',
    product: 'Milk',
    multiply: 1,
    price: 1,
    email: 'email',
  },
  {
    id: 1,
    category: 'Food',
    product: 'Fish',
    multiply: 2,
    price: 2,
    email: 'email',
  },
  {
    id: 2,
    category: 'Car',
    product: 'Doors',
    multiply: 3,
    price: 3,
    email: 'email',
  },
  {
    id: 3,
    category: 'Car',
    product: 'Window',
    multiply: 4,
    price: 4,
    email: 'email',
  },
  {
    id: 4,
    category: 'Home',
    product: 'Color',
    multiply: 5,
    price: 5,
    email: 'email',
  },
  {
    id: 5,
    category: 'Home',
    product: 'Window',
    multiply: 6,
    price: 6,
    email: 'email',
  },
  {
    id: 6,
    category: 'Home',
    product: 'Doors',
    multiply: 7,
    price: 7,
    email: 'email',
  },
  {
    id: 7,
    category: 'Food',
    product: 'Chips',
    multiply: 8,
    price: 8,
    email: 'email',
  },
  {
    id: 8,
    category: 'Food',
    product: 'Kebab',
    multiply: 9,
    price: 9,
    email: 'email',
  },
];
